name: Function App CI/CD sample

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - './src/**'
      - '.github/workflows/function-app-cicd-sample.yml'
      
env:
  DOTNET_VERSION: '6.0.x'
  # Function App1
  AZURE_FUNCTIONAPP1_PACKAGE_PATH: 'src/CognitiveSearchSamples'
  AZURE_FUNCTIONAPP1_NAME: 'func-zen-aoai-searchindex-management'
  # Function App2
  AZURE_FUNCTIONAPP2_PACKAGE_PATH: 'src/CosmosDataUploader'
  AZURE_FUNCTIONAPP2_NAME: 'func-zen-aoai-cosmos-uploader' 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: dotnet publish (Function App1)
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP1_PACKAGE_PATH }}'
        dotnet publish --configuration Release --output ${{ github.workspace }}/outputs/${{ env.AZURE_FUNCTIONAPP1_NAME }}
        popd
        
    - name: dotnet publish (Function App2)
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP2_PACKAGE_PATH }}'
        dotnet publish --configuration Release --output ${{ github.workspace }}/outputs/${{ env.AZURE_FUNCTIONAPP2_NAME }}
        popd
        
    - name: Upload artifacts (Function App1)
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AZURE_FUNCTIONAPP1_NAME }}
        path: ${{ github.workspace }}/outputs/${{ env.AZURE_FUNCTIONAPP1_NAME }}

    - name: Upload artifacts (Function App2)
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AZURE_FUNCTIONAPP2_NAME }}
        path: ${{ github.workspace }}/outputs/${{ env.AZURE_FUNCTIONAPP2_NAME }}

  deploy-function1:
    name: Deploy Function App1
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact (Function App1)
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AZURE_FUNCTIONAPP1_NAME }}
          path: artifacts
          
      - name: Deploy (Function App1)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP1_NAME }}
          package: artifacts/${{ env.AZURE_FUNCTIONAPP1_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP1_PUBLISH_PROFILE }}
          
  deploy-function2:
    name: Deploy Function App2
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact (Function App2)
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AZURE_FUNCTIONAPP2_NAME }}
          path: artifacts
          
      - name: Deploy (Function App2)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP2_NAME }}
          package: artifacts/${{ env.AZURE_FUNCTIONAPP2_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP2_PUBLISH_PROFILE }}
